global_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5
  publish_frequency: 2
  static_map: false
  rolling_window: true
  width: 100.0
  height: 100.0
  resolution: 0.05
  plugins:
   -
     name: footprint
     type: "costmap_2d::FootprintLayer"
   - 
     name: obstacles
     type: "costmap_2d::ObstacleLayer"
   - 
     name: inflater
     type: "costmap_2d::InflationLayer"
