#!/usr/bin/env python

import os
import robot_upstart

j = robot_upstart.Job(workspace_setup=os.environ['ROBOT_SETUP'])
j.add(package="jackal_base", filename="launch/base.launch")
j.add(package="jackal_bringup", filename="launch/accessories.launch")
j.install()
